<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dasar_sip_model extends CI_Model
{

    public $table = 'dasar_sip';
    public $id = 'id_dasar_sip';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('dasar_sip.id_dasar_sip', $id);
        $this->db->join('jenis_dasar_sip', 'jenis_dasar_sip.id_jenis_dasar_sip=dasar_sip.id_jenis_dasar_sip');
        $this->db->join('nakes', 'nakes.id_nakes=dasar_sip.id_nakes');
        $this->db->select('dasar_sip.id_dasar_sip');
        $this->db->select('jenis_dasar_sip');
        $this->db->select('nama');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_dasar_sip', $q);
	$this->db->or_like('id_jenis_dasar_sip', $q);
	$this->db->or_like('id_nakes', $q);
	$this->db->or_like('masa_berlaku', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dasar_sip', $q);
	$this->db->or_like('dasar_sip.id_jenis_dasar_sip', $q);
	$this->db->or_like('dasar_sip.id_nakes', $q);
	$this->db->or_like('masa_berlaku', $q);
	$this->db->limit($limit, $start);
    $this->db->join('jenis_dasar_sip', 'jenis_dasar_sip.id_jenis_dasar_sip=dasar_sip.id_jenis_dasar_sip');
    $this->db->join('nakes', 'nakes.id_nakes=dasar_sip.id_nakes');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dasar_sip_model.php */
/* Location: ./application/models/Dasar_sip_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-25 03:25:58 */
/* http://harviacode.com */