<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sarkes_model extends CI_Model
{

    public $table = 'sarkes';
    public $id = 'id_sarkes';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('sarkes.id_sarkes', $id);
        $this->db->join('jenis_sarkes', 'jenis_sarkes.id_jenis_sarkes=sarkes.id_jenis_sarkes');
        $this->db->join('kecamatan', 'kecamatan.id_kecamatan=sarkes.id_kecamatan');
        $this->db->join('kelurahan', 'kelurahan.id_kelurahan=sarkes.id_kelurahan');
        $this->db->select('sarkes.id_sarkes');
        $this->db->select('sarkes.id_jenis_sarkes');
        $this->db->select('sarkes.id_kecamatan');
        $this->db->select('sarkes.id_kelurahan');
        $this->db->select('jenis_sarkes');
        $this->db->select('kecamatan');
        $this->db->select('kelurahan');
        $this->db->select('sarkes');
        $this->db->select('alamat_sarkes');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sarkes', $q);
	$this->db->or_like('id_jenis_sarkes', $q);
	$this->db->or_like('id_kecamatan', $q);
	$this->db->or_like('id_kelurahan', $q);
	$this->db->or_like('sarkes', $q);
	$this->db->or_like('alamat_sarkes', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sarkes', $q);
	$this->db->or_like('sarkes.id_jenis_sarkes', $q);
	$this->db->or_like('sarkes.id_kecamatan', $q);
	$this->db->or_like('sarkes.id_kelurahan', $q);
	$this->db->or_like('sarkes', $q);
	$this->db->or_like('alamat_sarkes', $q);
	$this->db->limit($limit, $start);
    $this->db->join('jenis_sarkes', 'jenis_sarkes.id_jenis_sarkes=sarkes.id_jenis_sarkes');
    $this->db->join('kecamatan', 'kecamatan.id_kecamatan=sarkes.id_kecamatan');
    $this->db->join('kelurahan', 'kelurahan.id_kelurahan=sarkes.id_kelurahan');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function data_kecamatan($id_kecamatan)
    {
      $this->db->where('id_kecamatan', $id_kecamatan);
  $this->db->order_by('kelurahan', 'ASC');
  $query = $this->db->get('kelurahan');
  foreach($query->result() as $row)
  {
   $output .= '<option value="'.$row->id_kelurahan.'">'.$row->kelurahan.'</option>';
  }
  return $output;
    }


}

/* End of file Sarkes_model.php */
/* Location: ./application/models/Sarkes_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-25 03:25:58 */
/* http://harviacode.com */